### ISSUE TITLE
How can we use LogstashTcpSocketAppender from logstash-logback-encoder

### ISSUE THREAD

**Issue by rohitpas** [tomcat-slf4j-logback/tomcat7-slf4j-logback#17]
I wan't to use LogstashTcpSocketAppender (from logstash-logback-encoder) in tomcat - 7.0.107 to send the logs to ELK.
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>5.3</version>
        </dependency>

**Comment by hazendaz** [comment]
some work was tried upstream but in IMHO brings in far too much to this project bloating it significantly.  Try looking at the supported tomcats.  Tomcat 7 is no longer supported.

**Comment by hazendaz** [comment]
See here https://github.com/tomcat-slf4j-logback/tomcat9-slf4j-logback/pull/20
